# Generated by Django 3.0.5 on 2024-03-20 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_table',
            name='answer',
        ),
        migrations.CreateModel(
            name='question_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionkey', models.CharField(max_length=50)),
                ('QUESTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SE.question_table')),
            ],
        ),
    ]
